### ISSUE TITLE
[pending upstream changes] Transaction support

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#30] opened 2016-03-16 19:27 UTC
Many of the ops need to happen inside a transaction; this is currently not supported under `orientdb-gremlin`: orientdb-gremlin/issues/16

TODO: think about equivalent on IPFS

**Comment by yusefnapora** [comment] 2016-03-16 20:25
Maybe transactions are supported after all...

This got merged in November: https://github.com/mpollmeier/orientdb-gremlin/pull/17
but the issue is still open.  I'll dig into the code a bit and see if I can sort it out

**Comment by parkan** [comment] 2016-03-31 17:01
This appears to be addressed in 15f1462bea96cd80948af718877202b11ef51724

I see `withTransaction` used in `Merge`, I guess we should switch to it in `Ingress` as well? Do we still need monadic transaction support or is this good enough?

**Comment by yusefnapora** [comment] 2016-03-31 17:15
I haven't thoroughly nested transactions yet, but I think they should work.

**Comment by bigs** [comment] 2016-04-01 15:53
on advantage of a monadic transaction API would be transaction flattening i.e. only a single layer

**Comment by parkan** [comment] 2016-04-01 17:03
@bigs my understanding was that there is no nested transaction support at all, so we already kind of address that here: https://github.com/mediachain/L-SPACE/commit/15f1462bea96cd80948af718877202b11ef51724#diff-c146692e98427deb835eca75000291daR27

or do you mean something else?

**Comment by bigs** [comment] 2016-04-04 15:08
@parkan i think the worry was that the transaction support was more or less a no-op. @yusefnapora?

**Comment by yusefnapora** [comment] 2016-04-04 15:09
@bigs, transactions are only a no-op if you use `OrientGraphFactory().getNoTx()`.  But we switched over to `getTx()` when we started creating vertex and edge classes with the migration stuff.  So they should be enabled now

**Comment by parkan** [comment] 2016-04-07 19:05
Some issues with this tracked down and addressed by the fearless yusef in https://github.com/mediachain/L-SPACE/pull/49/commits/047e41a76dd7ada956d82265ce3ba6f1c6f5a047

**Closed** 2016-04-21 20:36 UTC
